## Pivot Table and Melt function

Melt

In [1]:
import pandas as pd

In [2]:
var = pd.DataFrame({"day":[1,2,3,4,5,6],"eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})
var

   day  eng  math
0    1   10    17
1    2   12    18
2    3   14    19
3    4   15    13
4    5   16    14
5    6   12    16

In [3]:
pd.melt(var)

   variable  value
0       day      1
1       day      2
2       day      3
3       day      4
4       day      5
5       day      6
6       eng     10
7       eng     12
8       eng     14
9       eng     15
10      eng     16
11      eng     12
12     math     17
13     math     18
14     math     19
15     math     13
16     math     14
17     math     16

In [4]:
pd.melt(var,id_vars=['eng'])

    eng variable  value
0    10      day      1
1    12      day      2
2    14      day      3
3    15      day      4
4    16      day      5
5    12      day      6
6    10     math     17
7    12     math     18
8    14     math     19
9    15     math     13
10   16     math     14
11   12     math     16

In [5]:
pd.melt(var,id_vars=['day'])

    day variable  value
0     1      eng     10
1     2      eng     12
2     3      eng     14
3     4      eng     15
4     5      eng     16
5     6      eng     12
6     1     math     17
7     2     math     18
8     3     math     19
9     4     math     13
10    5     math     14
11    6     math     16

In [6]:
pd.melt(var,id_vars=['day'],var_name="python")

    day python  value
0     1    eng     10
1     2    eng     12
2     3    eng     14
3     4    eng     15
4     5    eng     16
5     6    eng     12
6     1   math     17
7     2   math     18
8     3   math     19
9     4   math     13
10    5   math     14
11    6   math     16

In [7]:
pd.melt(var,id_vars=['day'],var_name="python",value_name="wscube")

    day python  wscube
0     1    eng      10
1     2    eng      12
2     3    eng      14
3     4    eng      15
4     5    eng      16
5     6    eng      12
6     1   math      17
7     2   math      18
8     3   math      19
9     4   math      13
10    5   math      14
11    6   math      16

Pivot

In [8]:
var1 = pd.DataFrame({"day":[1,2,3,4,5,6],
                    "st_name":['a','b','c','a','b','c'],"eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})

var1

   day st_name  eng  math
0    1       a   10    17
1    2       b   12    18
2    3       c   14    19
3    4       a   15    13
4    5       b   16    14
5    6       c   12    16

In [9]:
var1.pivot(index='day',columns='st_name')

          eng              math
st_name     a     b     c     a     b     c
day
1        10.0   NaN   NaN  17.0   NaN   NaN
2         NaN  12.0   NaN   NaN  18.0   NaN
3         NaN   NaN  14.0   NaN   NaN  19.0
4        15.0   NaN   NaN  13.0   NaN   NaN
5         NaN  16.0   NaN   NaN  14.0   NaN
6         NaN   NaN  12.0   NaN   NaN  16.0

In [10]:
var1 = pd.DataFrame({"day":[1,2,3,4,5,6],
                    "st_name":['a','b','a','a','b','b'],"eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})

var1

   day st_name  eng  math
0    1       a   10    17
1    2       b   12    18
2    3       a   14    19
3    4       a   15    13
4    5       b   16    14
5    6       b   12    16

In [11]:
var1.pivot(index='day',columns='st_name')

          eng        math
st_name     a     b     a     b
day
1        10.0   NaN  17.0   NaN
2         NaN  12.0   NaN  18.0
3        14.0   NaN  19.0   NaN
4        15.0   NaN  13.0   NaN
5         NaN  16.0   NaN  14.0
6         NaN  12.0   NaN  16.0

In [12]:
## we only wanna see the data of the english
## we can access the data of the particulat columns

var1.pivot(index='day',columns='st_name', values='eng')

st_name     a     b
day
1        10.0   NaN
2         NaN  12.0
3        14.0   NaN
4        15.0   NaN
5         NaN  16.0
6         NaN  12.0

In [13]:
var1 = pd.DataFrame({"day":[1,1,1,1,2,2],
                    "st_name":['a','b','a','a','b','b'],"eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})

var1

   day st_name  eng  math
0    1       a   10    17
1    1       b   12    18
2    1       a   14    19
3    1       a   15    13
4    2       b   16    14
5    2       b   12    16

In [14]:
var1.pivot_table(index='st_name',columns='day')

          eng             math
day         1     2          1     2
st_name
a        13.0   NaN  16.333333   NaN
b        12.0  14.0  18.000000  15.0

In [15]:
## we can use the aggfunc to perform the mean max minimu 
var1.pivot_table(index='st_name',columns='day',aggfunc="max")

          eng        math
day         1     2     1     2
st_name
a        15.0   NaN  19.0   NaN
b        12.0  16.0  18.0  16.0

In [16]:
## margin give the average value
var1.pivot_table(index='st_name',columns='day',aggfunc="sum",margins="True")

          eng            math
day         1     2 All     1     2 All
st_name
a        39.0   NaN  39  49.0   NaN  49
b        12.0  28.0  40  18.0  30.0  48
All      51.0  28.0  79  67.0  30.0  97

In [17]:
## margin give the average value
var1.pivot_table(index='st_name',columns='day',aggfunc="mean",margins="True")

           eng                        math
day          1     2        All          1     2        All
st_name
a        13.00   NaN  13.000000  16.333333   NaN  16.333333
b        12.00  14.0  13.333333  18.000000  15.0  16.000000
All      12.75  14.0  13.166667  16.750000  15.0  16.166667