## Arithmatic Operator in Pandas

In [1]:
import pandas as pd

var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,3,9]})
print(var)

   A  B
0  1  5
1  2  6
2  3  3
3  4  9

In [2]:
## addition of both column

var["c"] = var["A"] + var["B"]
var

   A  B   c
0  1  5   6
1  2  6   8
2  3  3   6
3  4  9  13

In [3]:
## multiplication of both column

var["c"] = var["A"] * var["B"]
var

   A  B   c
0  1  5   5
1  2  6  12
2  3  3   9
3  4  9  36

In [4]:
var1 = pd.DataFrame({"a":[10,20,30,40],"b":[15,16,17,18]})
print(var1)

    a   b
0  10  15
1  20  16
2  30  17
3  40  18

In [5]:
var1["python"] = var1["a"] <= 20
print(var1)

    a   b  python
0  10  15    True
1  20  16    True
2  30  17   False
3  40  18   False

In [6]:
var1["python"] = var1["b"] <= 16
print(var1)

    a   b  python
0  10  15    True
1  20  16    True
2  30  17   False
3  40  18   False