## Insert and Delete

In [1]:
import pandas as pd
var = pd.DataFrame({"A":[1,2,3,4],"B":[9,8,7,6]})
var

   A  B
0  1  9
1  2  8
2  3  7
3  4  6

In [2]:
var.insert(1,"Python",var["A"])

In [3]:
var

   A  Python  B
0  1       1  9
1  2       2  8
2  3       3  7
3  4       4  6

In [4]:
var.insert(1,"Id_num",[22,12,34,54])

In [5]:
var

   A  Id_num  Python  B
0  1      22       1  9
1  2      12       2  8
2  3      34       3  7
3  4      54       4  6

In [6]:
import pandas as pd
var = pd.DataFrame({"A":[1,2,3,4,5],"B":[9,8,7,6,7]})
var

   A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  7

In [7]:
var["Python_2"] = var["A"][:3]

In [8]:
var

   A  B  Python_2
0  1  9       1.0
1  2  8       2.0
2  3  7       3.0
3  4  6       NaN
4  5  7       NaN

## Delete

In [9]:
var.pop("B")

0    9
1    8
2    7
3    6
4    7
Name: B, dtype: int64

In [10]:
var

   A  Python_2
0  1       1.0
1  2       2.0
2  3       3.0
3  4       NaN
4  5       NaN

In [11]:
del var["A"]

In [12]:
var

   Python_2
0       1.0
1       2.0
2       3.0
3       NaN
4       NaN